version: '3.8'

services:
  mongosqld:
    container_name: mongosqld
    hostname: mongosqld
    build:
      context: .
      args:
        VERSION: ${VERSION}
    image: ianblenke/mongosqld:${VERSION}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
        MONGODB_URL: ${MONGODB_URL}

